"""empty message

Revision ID: 3fb66325209d
Revises: cd52317c3602
Create Date: 2021-03-24 14:37:07.889689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb66325209d'
down_revision = 'cd52317c3602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chocolate', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chocolate', 'posted')
    # ### end Alembic commands ###
