"""empty message

Revision ID: 4e1111567350
Revises: 858df6407383
Create Date: 2021-03-30 00:45:15.959256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1111567350'
down_revision = '858df6407383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Chocolatier_name_key', 'Chocolatier', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Chocolatier_name_key', 'Chocolatier', ['name'])
    # ### end Alembic commands ###
