"""empty message

Revision ID: cd52317c3602
Revises: d8f3fc9a7cd5
Create Date: 2021-03-24 12:55:46.516123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd52317c3602'
down_revision = 'd8f3fc9a7cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chocolate', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Chocolate', 'Chocolatier', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chocolate', type_='foreignkey')
    op.drop_column('Chocolate', 'vendor_id')
    # ### end Alembic commands ###
