"""empty message

Revision ID: d8f3fc9a7cd5
Revises: 
Create Date: 2021-03-23 05:59:57.275634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f3fc9a7cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chocolatier', sa.Column('facebook', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chocolatier', 'facebook')
    # ### end Alembic commands ###
